### ISSUE TITLE
Lab 2 - Internal Server Error in Report Generator

### ISSUE THREAD

**Issue by alexeisersun** [Alexx-G/PR-labs#4]
I'm getting Internal Server Error when trying get `orders` for one single day i.e. `url/?start=2001-01-01&end=2001-01-01`.

Here's the error page:
`<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v101/orders/. Reason:
<pre>    Assert failed: (&lt;= min max)</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>`

**Comment by alexgavrisco** [comment]
Good catch! Fixed.
